title: Notes
description: My Personal Note Book
author: Jimmy Sue
github: https://github.com/jimmysue
about: Currently working for meitu.com as a computer vision engineer.
disqus_shortname: notes
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/fjsjinz"
    - icon: fa-weibo
      link: 'http://weibo.com/u/3304045554'


#share:
#  twitter_username: agusmakmun6
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Category
      url: /categoryview/
    - text: Github
      url: https://github.com/jimmysue
    - text: XML Feed
      url: /feed.xml

url: "https://jimmysue.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist